name: Deploy to Firebase Functions and Hosting

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build
        env:
          VITE_MAINAPI: ${{ vars.VITE_MAINAPI }}
        run: CI=false npm run build

      - name: Deploy to Firebase
        run: firebase deploy --only hosting,functions --token ${{ secrets.FIREBASE_TOKEN }} --project dev --force
